const WEEKLY_STEP_COUNT = 'WEEKLY_STEP_COUNT';
const WEEKLY_HEART_POINTS = 'WEEKLY_HEART_POINTS';
const WEEKLY_CALORIES_BURNED = 'WEEKLY_CALORIES_BURNED';
const GET_WEEKLY_DATA = 'GET_WEEKLY_DATA';

export default {
    WEEKLY_STEP_COUNT,
    WEEKLY_HEART_POINTS,
    WEEKLY_CALORIES_BURNED,
    GET_WEEKLY_DATA,
}