const WEEKLY_STEP_COUNT = 'WEEKLY_STEP_COUNT';
const WEEKLY_HEART_POINTS = 'WEEKLY_HEART_POINTS';
const WEEKLY_CALORIES_BURNED = 'WEEKLY_CALORIES_BURNED';
const MONTHLY_STEP_COUNT = 'MONTHLY_STEP_COUNT';
const MONTHLY_HEART_POINTS = 'MONTHLY_HEART_POINTS';
const MONTHLY_CALORIES_BURNED = 'MONTHLY_CALORIES_BURNED';
const GET_WEEKLY_DATA = 'GET_WEEKLY_DATA';
const GET_MONTHLY_DATA = 'GET_MONTHLY_DATA';

export default {
    WEEKLY_STEP_COUNT,
    WEEKLY_HEART_POINTS,
    WEEKLY_CALORIES_BURNED,
    MONTHLY_STEP_COUNT,
    MONTHLY_HEART_POINTS,
    MONTHLY_CALORIES_BURNED,
    GET_WEEKLY_DATA,
    GET_MONTHLY_DATA
}