const STEP_COUNT = 'STEP_COUNT';
const HEART_POINTS = 'HEART_POINTS';
const CALORIES_BURNED = 'CALORIES_BURNED';
const GET_WEEKLY_DATA = 'GET_WEEKLY_DATA';

export default {
    STEP_COUNT,
    HEART_POINTS,
    CALORIES_BURNED,
    GET_WEEKLY_DATA,
}